### ISSUE TITLE
Server doesn't restart, backups don't run

### ISSUE THREAD

**Issue by 407pilot** [TheRemote/Legendary-Java-Minecraft-Paper#2]
I haven't had a single backup run and the server does not restart. All I changed from the sample docker compose file is the volume location, uncommented the options I wanted, and changed the time zone. 

```
# Minecraft Java Paper Server + Geyser + Floodgate Docker Container - Docker Compose
# Author: James A. Chambers - https://jamesachambers.com/minecraft-java-bedrock-server-together-geyser-floodgate/
# GitHub Repository: https://github.com/TheRemote/Legendary-Java-Minecraft-Geyser-Floodgate

# To run multiple servers change the volume name under both "volumes" sections and select different ports
version: "3.5"
services:
  minecraftbe:
    image: 05jchambers/legendary-minecraft-geyser-floodgate:latest
    restart: "unless-stopped"
    ports:
      - 25565:25565
      - 19132:19132
      - 19132:19132/udp
    volumes:
      - /home/minecraft/minecraft:/minecraft
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: [ "/bin/bash", "/scripts/start.sh" ]
    # Environment variables
    environment:
      Port: "25565"
      BedrockPort: "19132"
      TZ: "America/Chicago" # Timezone
      BackupCount: 10 # Number of rolling backups to keep
      MaxMemory: 2048 # Maximum memory usage for Java
      #Version: 1.19.3 # Use custom version
      #NoBackup: "plugins" # Optional folder to skip during backups
      #NoPermCheck: "Y" # Optional flag to skip permissions check
      #QuietCurl: "Y" # Optional flag to reduce curl log output by suppressing progress meter
      ScheduleRestart: "3:30" # Optional restart -- specify time in 24 hour format
volumes:
  minecraft:
    driver: local
```
